version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/users_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: pp_user
      SPRING_DATASOURCE_PASSWORD: pp_user

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: pp_user
      MYSQL_PASSWORD: pp_user
      MYSQL_ROOT_PASSWORD: root_password